services:

  inginious-db:
    image: mongo:6.0.2
    networks:
      - inginious

  inginious-backend:
    image: inginious/inginious-backend
    build:
      dockerfile: deploy/backend.containerfile
    environment:
      AGENT: "tcp://0.0.0.0:2001"
      CLIENT: "tcp://0.0.0.0:2000"
    networks:
      - inginious

  inginious-agent-docker:
    image: inginious/inginious-agent-docker
    depends_on:
      - inginious-backend
    deploy:
      replicas: 1
    build:
      dockerfile: deploy/agent-docker.containerfile
    environment:
      BACKEND: "tcp://inginious-backend:2001"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     # See https://github.com/UCL-INGI/INGInious/issues/352
     - ./tasks/:/inginious/tasks
     - ./backups/:/inginious/backups
     # See https://github.com/UCL-INGI/INGInious/issues/799
     - /tmp/agent_data/:/tmp/agent_data/
    networks:
      - inginious

  inginious-agent-mcq:
    image: inginious/inginious-agent-mcq
    depends_on:
      - inginious-backend
    deploy:
      replicas: 1
    build:
      dockerfile: deploy/agent-mcq.containerfile
    environment:
      BACKEND: "tcp://inginious-backend:2001"
    volumes:
     # See https://github.com/UCL-INGI/INGInious/issues/352
     - ./tasks/:/inginious/tasks
     - ./backups/:/inginious/backups
     # See https://github.com/UCL-INGI/INGInious/issues/799
     - /tmp/agent_data/:/tmp/agent_data/
    networks:
      - inginious

  inginious-frontend:
    image: inginious/inginious-frontend
    build:
      dockerfile: deploy/frontend.containerfile
    depends_on:
      - inginious-backend
      - inginious-agent-docker
      - inginious-agent-mcq
    environment:
      - INGINIOUS_WEBAPP_HOST=0.0.0.0
    volumes:
      - ./configuration.deploy.yaml:/inginious/configuration.yaml
      - ./tasks/:/inginious/tasks
      - ./backups/:/inginious/backups
    ports:
      - 9000:8080
    networks:
      - inginious

networks:
  inginious:
