services:

  inginious-db:
    image: mongo:6.0.2
    networks:
      - inginious

  inginious-backend:
    image: inginious/inginious-backend
    build:
      dockerfile: deploy/backend.containerfile
    environment:
      AGENT: "tcp://0.0.0.0:2001"
      CLIENT: "tcp://0.0.0.0:2000"
    networks:
      - inginious

  inginious-agent-docker:
    image: inginious/inginious-agent-docker
    depends_on:
      - inginious-backend
    deploy:
      replicas: 1
    build:
      dockerfile: deploy/agent-docker.containerfile
    environment:
      BACKEND: "tcp://inginious-backend:2001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inginious

  inginious-agent-mcq:
    image: inginious/inginious-agent-mcq
    depends_on:
      - inginious-backend
    deploy:
      replicas: 1
    build:
      dockerfile: deploy/agent-mcq.containerfile
    environment:
      BACKEND: "tcp://inginious-backend:2001"
    networks:
      - inginious

networks:
  inginious:
