services:

  inginious-backend:
    image: inginious-backend
    build:
      dockerfile: backend.containerfile
    environment:
      AGENT: "tcp://0.0.0.0:2001"
      CLIENT: "tcp://0.0.0.0:2000"
    networks:
      - inginious

  inginious-agent-docker:
    image: inginious-agent-docker
    deploy:
      replicas: 1
    build:
      dockerfile: agent-docker.containerfile
    environment:
      BACKEND: "tcp://inginious-backend:2001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inginious

  inginious-agent-mcq:
    image: inginious-agent-mcq
    deploy:
      replicas: 1
    build:
      dockerfile: agent-mcq.containerfile
    environment:
      BACKEND: "tcp://inginious-backend:2001"
    networks:
      - inginious

networks:
  inginious:
